### ISSUE TITLE
Error when using a language other than English, for example nl_BE, pt_BR among others.

### ISSUE THREAD

**Issue by gustotc** [novacode-nl/odoo-formio#93]
following image below the JS error
Updated version
Odoo version 12.0
[formio_translations_pt_BR.xml.zip](https://github.com/novacode-nl/odoo-formio/files/5661501/formio_translations_pt_BR.xml.zip)

![image](https://user-images.githubusercontent.com/7175315/101530508-c5a55800-3970-11eb-8c09-609c68f0b7e8.png)

**Comment by bobslee** [comment]
@gustotc Thanks for your issue report.
Few days ago I pushed a change for version `12.0` and `13.0` which addresses similar issue: https://github.com/novacode-nl/odoo-formio/commit/6e192fcaf04bb21c468a84014dddaabf5e49dec6

You already updated to the latest  version `12.0` or `13.0` of the **formio** module?
Keep me posted please.

**Comment by gustotc** [comment]
@bobslee, thanks for the feedback,

Yes, I updated it yesterday.

Before the update he always assumed the language "EN" then the fields in English worked, but after its correction and takes the correct language, however it gives the error in the JS of the image.

It gives error in JS and does not mount any field, if I leave it in 'EN' the language assembles the screen.

**Comment by bobslee** [comment]
@gustotc, thanks for your reply.
I can reproduce a similar error. Shall fix this soon. Keep you posted!

**Comment by bobslee** [comment]
@gustotc  I think I solved this implementation. Shall push very soon (within hours).

**Comment by gustotc** [comment]
@bobslee 

Thanks for listening ...

**Comment by bobslee** [comment]
@gustotc Please download and replace `formio` with version 8.1
Should be fixed now.
Let me know or close the issue :)

**Comment by bobslee** [comment]
@gustotc by the way... I added your translations into the`formio` module. Thanks!

**Comment by gustotc** [comment]
@bobslee 

Thank you very much

What I can help you can count on me, including the translation of the module to pt_BR, if you want. If so, I'll send you the file.

**Comment by bobslee** [comment]
@gustotc Yes please send me the translation files. 

Would be glad if you could contribute by any means.
Take care!

**Comment by gustotc** [comment]
@bobslee 

It follows pt_br translation files by module, already separated by module folder.

Best regards,

[translate_pt_BR_per_Module.zip](https://github.com/novacode-nl/odoo-formio/files/5668339/translate_pt_BR_per_Module.zip)

**Comment by gustotc** [comment]
@bobslee 

I had to reopen the error, because:
In the Construction of the Form it worked perfectly, however in the visualization in the CRM module it has the error.

![image](https://user-images.githubusercontent.com/7175315/101683665-0621d600-3a44-11eb-8850-74b0f14c0c2d.png)


![image](https://user-images.githubusercontent.com/7175315/101683713-1934a600-3a44-11eb-9f1a-a5b58683ae2b.png)

**Comment by bobslee** [comment]
@gustotc Unfortunately I can't reproduce the error.

Please could you provide more info/data?
I would like to test with your Form Builder `schema` (field data). Could you it share with me?
Of course you can mail the `schema` (field data) to me: `bob (at) novacode (dot) nl`

**Comment by bobslee** [comment]
Just found an issue with language switcher and language code. Still working on...

**Comment by bobslee** [comment]
@gustotc Please download and update to version 8.2 (formio).
I resolved and improved some issues with the language switcher (buttons) and also translations should work now.
I tested thoroughly, so I'm curious whether it works with you.

**Comment by gustotc** [comment]
@bobslee 

sorry, i just saw your message now.

If you still want I can send the form without any problem, but as you generated a new version I will test it well and return.

Thank you very much for your attention and count on me to test and report and if you allow it, I can also try to identify maybe improvements and post for you to see if it is useful.

Thank you again,

Best Regards

**Comment by gustotc** [comment]
@bobslee 

unfortunately the error still occurs. I will try to explain it better.

I'm using your demo model, in the commercial module.

When I edit the form, it works perfectly, but when I enter the commercial module, select a sale and click on the form button to complete it, it does not load the fields and in the browse console shows the image error.

However, if fixed in the language 'EN' it works, load the fields for filling. I also tested by modifying the language to another language "nt_BE" and the error also occurs.

![image](https://user-images.githubusercontent.com/7175315/101707213-8e66a200-3a69-11eb-8a70-39a4d2ace793.png)

![image](https://user-images.githubusercontent.com/7175315/101707221-94f51980-3a69-11eb-82b8-7e0a4aab0e1d.png)

**Comment by niulinlnc** [comment]
@bobslee After version 14 was updated to the latest, there were similar problems. If I set up a non-English environment (such as simplified Chinese) in Odoo and added a translation package (simplified Chinese) to my Builder, I wouldn't be able to pop up a dialog box when the builder builds a field.

**Comment by niulinlnc** [comment]
@bobslee  Please see the following steps for replicating:
![001](https://user-images.githubusercontent.com/11767049/101712440-7e35dd80-3ad0-11eb-9c1e-c774d31d8011.png)
![002](https://user-images.githubusercontent.com/11767049/101712447-8261fb00-3ad0-11eb-83a6-291853638928.png)
![003](https://user-images.githubusercontent.com/11767049/101712454-855ceb80-3ad0-11eb-903e-00cc14dce37d.png)
![004](https://user-images.githubusercontent.com/11767049/101712460-8857dc00-3ad0-11eb-96aa-56682f81a464.png)

**Comment by bobslee** [comment]
Thanks for reporting. I'll come back to this within a few days (weekend).
I've some clues how to analyse/debug and hopefully solve.

**Comment by gustotc** [comment]
> Thanks for reporting. I'll come back to this within a few days (weekend).
> I've some clues how to analyse/debug and hopefully solve.


Thank you very much, good weekend, rest to recharge your batteries.

**Comment by bobslee** [comment]
@gustotc reproduced the issue and finally solved on my local development env. 

Issue is due to formatting the language code with an underscore "_", whereas the Formio JS implementation expects a hyphen "-". 

Before I push the change, I improve the code and shall test again.

This is also related to #95

**Comment by bobslee** [comment]
@gustotc Issue should be solved now. 
Please download and upgrade to `formio` version 8.3. Clear your webbrowser cachte too.
Let me know if any further issues regarding translations and language switcher.

**Comment by gustotc** [comment]
> I reproduced the issue and finally solved on my local development env.
> 
> Issue is due to formatting the language code with an underscore "_", whereas the Formio JS implementation expects a hyphen "-".
> 
> Before I push the change, I improve the code and shall test again.
> 
> This is also related to #91, #95

good news

Thank you.

**Comment by gustotc** [comment]
> Issue should be solved now.
> Please download and upgrade to `formio` version 8.3. Clear your webbrowser cache too.
> Let me know if any further issues regarding translations and language switcher.

Okay, I'll do what you asked for, test it and let you know.

Thank you.

**Comment by bobslee** [comment]
> @bobslee
> 
> It follows pt_br translation files by module, already separated by module folder.
> 
> Best regards,
> 
> [translate_pt_BR_per_Module.zip](https://github.com/novacode-nl/odoo-formio/files/5668339/translate_pt_BR_per_Module.zip)

@gustotc I just added your `pt_BR` translations to the v12.0 branch.
For later versions, I hope you or somebody could maintain. Thanks!
